### ISSUE TITLE
New version breaks "pluggable" functionality of wordpress

### ISSUE THREAD

**Issue by daveagp** [Yoast/google-analytics-for-wordpress#271]
Hi,

Your newest version of google-analytics-for-wordpress has broken part of my site's functionality (though I just upgraded once after not upgrading for a few months). The problem is that your code breaks pluggable functions. On line 283 of frontend/abstract-class-tracking.php, you include "pluggable.php". Unfortunately, pluggable functions rely on that file, pluggable.php, being loaded after all plugins. 

I guess a fix would be if you can guarantee that your plugin is loaded last, though I don't know if other people have written their own plugins like that too, and you can't both be last. Or maybe you can rethink the timing of your plugin's sequence of events.

Thanks for an otherwise great plugin!

- Dave

**Comment by omarreiss** [comment]
Should be fixed now.
We'll run some tests before release to make sure this issue is actually resolved.

**Comment by daveagp** [comment]
Thanks! Looking forward to it.

**Comment by ChrisDean** [comment]
this issue appears to persist (upgraded today) is there an update pending release?

**Comment by andrebalza** [comment]
Issue persists and it's very annoying.Frontend topbar is broken and preview functionality too. Any chance for a quck fix?

**Comment by omarreiss** [comment]
@ChrisDean @andrebalza @daveagp we've released a beta which we plan to release next week. You can find it here: https://yoast.com/public-betas-plugins/

Please let us know if this fixes your problem.

**Comment by andrebalza** [comment]
beta plugin restores broken functionality, in my case. thank you @omarreiss
